services:
  db:
    image: postgis/postgis:16-3.4
    container_name: reforestation_db
    environment:
      - POSTGRES_USER=${DB_USER-admin}
      - POSTGRES_PASSWORD=${DB_PASS-password}
      - POSTGRES_DB=${DB_NAME-reforestation}
    ports:
      - "5432:5432" # Exposes the database to your host machine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reforestation"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: reforestation_backend
    ports:
      - "8000:8000" # Exposes the FastAPI backend
    # We no longer expose 8501, as frontend is separate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db # The backend container connects to the 'db' service
      - DB_USER=admin
      - DB_PASS=password
      - DB_NAME=reforestation
      - DB_PORT=5432

volumes:
  postgres_data:
    driver: local